name: Deploy MkDocs

on:
  push:
    paths:
      - 'Codes/**'
      - '.github/workflows/deploy.yml'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install dependencies
        run: |
          pip install -r req.txt

      - name: Prepare docs folder
        run: |
          mkdir -p docs
          cp Codes/* docs/

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
