name: Auto Update README from Codes

on:
  push:
    paths:
      - 'Codes/README.md'
  workflow_dispatch:  # manual trigger option

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run update_readme_colab.py
        run: python update_readme_colab.py

      - name: Commit and push changes if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Auto-update README from Codes/README.md"
          git push
